In [4]:
import numpy as np
import pandas as pd
import scanpy as sc

In [5]:
adata_path='/usr/src/app/storage/Benchmarks/dropletKidney_1755575402041/QC/annotation/a8ea5aeee7d3b8653cb8abf3ba9c2b22/droplet_Kidney_annotation.h5ad'
adata = sc.read_h5ad(adata_path)
adata

AnnData object with n_obs × n_vars = 2559 × 1738
    obs: 'orig.ident', 'n_counts', 'n_genes', 'channel', 'tissue', 'subtissue', 'mouse.sex', 'mouse.id', 'percent.ercc', 'percent.ribo', 'cell_ontology_class', 'res.0.5', 'previous_cell_ontology_class', 'cluster.ids', 'cell_ontology_id', 'pct_counts_mt', 'pct_counts_rb', 'pct_counts_hb', 'percent.plat', 'RNA_snn_res.0.5', 'seurat_clusters', 'doublet_score', 'doublet_class', 'leiden', 'louvain', 'split_idx', '_scvi_batch', '_scvi_labels', 'leiden_X_scVI', 'louvain_X_scVI', 'predicted_labels', 'over_clustering', 'majority_voting', 'conf_score', 'celltypist_label', 'celltypist_score', 'celltypist_ref_label', 'celltypist_ref_score', 'SingleR_main', 'SingleR_fine', 'SingleR_user_ref', 'Batch', 'scANVI_predicted', 'scANVI_transfer_score', 'X_scVI_leiden', 'X_scVI_louvain'
    var: 'vst.mean', 'vst.variance', 'vst.variance.expected', 'vst.variance.standardized', 'highly_variable', 'n_cells'
    uns: 'X_scVI_leiden', 'X_scVI_louvain', '_scvi_manager_uuid', '_scvi_uuid', 'leiden', 'leiden_X_scVI', 'log1p', 'louvain', 'louvain_X_scVI', 'neighbors', 'over_clustering', 'pca', 'rank_genes_groups'
    obsm: 'X_mde', 'X_pca', 'X_scVI', 'X_tsne', 'X_tsne_3D', 'X_umap', 'X_umap_3D'
    varm: 'PCs'
    layers: 'normalized_X', 'raw_counts', 'scale.data', 'scvi_normalized'
    obsp: 'connectivities', 'distances'

In [6]:
adata.obs = adata.obs.rename(columns={'ref_facs_Liver_Seurat_label': 'celltypist_ref_label', 'ref_facs_Liver_Seurat_score': 'celltypist_ref_score'})

In [7]:
adata.obs

,orig.ident,n_counts,n_genes,channel,tissue,subtissue,mouse.sex,mouse.id,percent.ercc,percent.ribo,...,celltypist_ref_label,celltypist_ref_score,SingleR_main,SingleR_fine,SingleR_user_ref,Batch,scANVI_predicted,scANVI_transfer_score,X_scVI_leiden,X_scVI_louvain
10X_P4_5_AAACCTGAGATGCCAG,10X,567.0,188,10X_P4_5,Kidney,,M,3-M-8,0.0,0.244693,...,leukocyte,0.698506,T cells,T cells,leukocyte,Unknown,leukocyte,0.360830,0,7
10X_P4_5_AAACCTGAGTGTCCAT,10X,810.0,251,10X_P4_5,Kidney,,M,3-M-8,0.0,0.081146,...,endothelial cell,0.999023,Endothelial cells,Endothelial cells,endothelial cell,Unknown,endothelial cell,0.978121,1,3
10X_P4_5_AAACCTGCAAGGCTCC,10X,1099.0,278,10X_P4_5,Kidney,,M,3-M-8,0.0,0.110893,...,endothelial cell,0.452945,Cardiomyocytes,Cardiomyocytes,endothelial cell,Unknown,endothelial cell,0.688448,2,8
10X_P4_5_AAACGGGAGCTGAACG,10X,512.0,179,10X_P4_5,Kidney,,M,3-M-8,0.0,0.098671,...,kidney collecting duct epithelial cell,0.933321,Oligodendrocytes,Hepatocytes,kidney collecting duct epithelial cell,Unknown,kidney collecting duct epithelial cell,0.817517,3,6
10X_P4_5_AAACGGGCAGGACCCT,10X,457.0,171,10X_P4_5,Kidney,,M,3-M-8,0.0,0.066408,...,epithelial cell of proximal tubule,0.938000,Hepatocytes,Hepatocytes,epithelial cell of proximal tubule,Unknown,epithelial cell of proximal tubule,0.971038,4,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10X_P7_5_TTTGCGCTCGGTTAAC,10X,1085.0,179,10X_P7_5,Kidney,,F,3-F-57,0.0,0.075776,...,kidney collecting duct epithelial cell,0.999838,Epithelial cells,Ependymal,kidney collecting duct epithelial cell,Unknown,kidney collecting duct epithelial cell,0.970771,3,5
10X_P7_5_TTTGTCAAGGCATTGG,10X,564.0,153,10X_P7_5,Kidney,,F,3-F-57,0.0,0.108880,...,kidney collecting duct epithelial cell,0.999072,Epithelial cells,Ependymal,kidney collecting duct epithelial cell,Unknown,kidney collecting duct epithelial cell,0.966201,6,1
10X_P7_5_TTTGTCACACGCCAGT,10X,469.0,110,10X_P7_5,Kidney,,F,3-F-57,0.0,0.079894,...,kidney collecting duct epithelial cell,0.999030,Epithelial cells,Ependymal,kidney collecting duct epithelial cell,Unknown,kidney collecting duct epithelial cell,0.933710,3,5
10X_P7_5_TTTGTCACATGGATGG,10X,803.0,193,10X_P7_5,Kidney,,F,3-F-57,0.0,0.098761,...,epithelial cell of proximal tubule,0.996598,Hepatocytes,Hepatocytes,epithelial cell of proximal tubule,Unknown,epithelial cell of proximal tubule,0.983485,4,4
10X_P7_5_TTTGTCAGTCCGACGT,10X,392.0,117,10X_P7_5,Kidney,,F,3-F-57,0.0,0.102564,...,epithelial cell of proximal tubule,0.999411,Hepatocytes,Hepatocytes,epithelial cell of proximal tubule,Unknown,epithelial cell of proximal tubule,0.980891,4,4

In [8]:
adata

AnnData object with n_obs × n_vars = 2559 × 1738
    obs: 'orig.ident', 'n_counts', 'n_genes', 'channel', 'tissue', 'subtissue', 'mouse.sex', 'mouse.id', 'percent.ercc', 'percent.ribo', 'cell_ontology_class', 'res.0.5', 'previous_cell_ontology_class', 'cluster.ids', 'cell_ontology_id', 'pct_counts_mt', 'pct_counts_rb', 'pct_counts_hb', 'percent.plat', 'RNA_snn_res.0.5', 'seurat_clusters', 'doublet_score', 'doublet_class', 'leiden', 'louvain', 'split_idx', '_scvi_batch', '_scvi_labels', 'leiden_X_scVI', 'louvain_X_scVI', 'predicted_labels', 'over_clustering', 'majority_voting', 'conf_score', 'celltypist_label', 'celltypist_score', 'celltypist_ref_label', 'celltypist_ref_score', 'SingleR_main', 'SingleR_fine', 'SingleR_user_ref', 'Batch', 'scANVI_predicted', 'scANVI_transfer_score', 'X_scVI_leiden', 'X_scVI_louvain'
    var: 'vst.mean', 'vst.variance', 'vst.variance.expected', 'vst.variance.standardized', 'highly_variable', 'n_cells'
    uns: 'X_scVI_leiden', 'X_scVI_louvain', '_scvi_manager_uuid', '_scvi_uuid', 'leiden', 'leiden_X_scVI', 'log1p', 'louvain', 'louvain_X_scVI', 'neighbors', 'over_clustering', 'pca', 'rank_genes_groups'
    obsm: 'X_mde', 'X_pca', 'X_scVI', 'X_tsne', 'X_tsne_3D', 'X_umap', 'X_umap_3D'
    varm: 'PCs'
    layers: 'normalized_X', 'raw_counts', 'scale.data', 'scvi_normalized'
    obsp: 'connectivities', 'distances'

In [9]:
adata.obs.leiden

10X_P4_5_AAACCTGAGATGCCAG     9
10X_P4_5_AAACCTGAGTGTCCAT     4
10X_P4_5_AAACCTGCAAGGCTCC    10
10X_P4_5_AAACGGGAGCTGAACG    11
10X_P4_5_AAACGGGCAGGACCCT     5
                             ..
10X_P7_5_TTTGCGCTCGGTTAAC     6
10X_P7_5_TTTGTCAAGGCATTGG     0
10X_P7_5_TTTGTCACACGCCAGT     6
10X_P7_5_TTTGTCACATGGATGG     2
10X_P7_5_TTTGTCAGTCCGACGT     2
Name: leiden, Length: 2559, dtype: category
Categories (14, object): ['0', '1', '2', '3', ..., '10', '11', '12', '13']

In [10]:
labels = adata.obs[['X_scVI_leiden', 'celltypist_label', 'celltypist_ref_label', 'SingleR_main', 'SingleR_fine', 'SingleR_user_ref', 'scANVI_predicted']].groupby('X_scVI_leiden').agg(lambda x: x.mode())
scores = adata.obs[['X_scVI_leiden', 'celltypist_score', 'celltypist_ref_score', 'scANVI_transfer_score']].groupby('X_scVI_leiden').agg(lambda x: x.mean())

mapping_res = labels.merge(right = scores, left_index=True, right_index=True)

/tmp/ipykernel_650/1872362096.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  labels = adata.obs[['X_scVI_leiden', 'celltypist_label', 'celltypist_ref_label', 'SingleR_main', 'SingleR_fine', 'SingleR_user_ref', 'scANVI_predicted']].groupby('X_scVI_leiden').agg(lambda x: x.mode())
/tmp/ipykernel_650/1872362096.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  scores = adata.obs[['X_scVI_leiden', 'celltypist_score', 'celltypist_ref_score', 'scANVI_transfer_score']].groupby('X_scVI_leiden').agg(lambda x: x.mean())

In [15]:
unique_values = labels.stack().unique()
unique_values

array(['Macrophage', 'macrophage', 'Monocytes', 'Macrophages',
       'capillary 2', 'endothelial cell', 'Endothelial cells',
       'Stromal cell (DN)', 'Fibroblasts', 'Cardiomyocytes',
       'enterocyte of epithelium of large intestine',
       'kidney collecting duct epithelial cell', 'Epithelial cells',
       'Ependymal', 'Enterocyte.dist',
       'epithelial cell of proximal tubule', 'Hepatocytes', 'EP'],
      dtype=object)

In [16]:
labels['majority_vote'] = labels.mode(axis=1)[0]
labels['majority_vote']

X_scVI_leiden
0                                macrophage
1                          endothelial cell
2                          endothelial cell
3    kidney collecting duct epithelial cell
4        epithelial cell of proximal tubule
5        epithelial cell of proximal tubule
6    kidney collecting duct epithelial cell
7    kidney collecting duct epithelial cell
Name: majority_vote, dtype: object

In [18]:
labels["cell_type"] = labels['majority_vote']
labels

,celltypist_label,celltypist_ref_label,SingleR_main,SingleR_fine,SingleR_user_ref,scANVI_predicted,majority_vote,cell_type
X_scVI_leiden,,,,,,,,
0,Macrophage,macrophage,Monocytes,Macrophages,macrophage,macrophage,macrophage,macrophage
1,capillary 2,endothelial cell,Endothelial cells,Endothelial cells,endothelial cell,endothelial cell,endothelial cell,endothelial cell
2,Stromal cell (DN),endothelial cell,Fibroblasts,Cardiomyocytes,endothelial cell,endothelial cell,endothelial cell,endothelial cell
3,enterocyte of epithelium of large intestine,kidney collecting duct epithelial cell,Epithelial cells,Ependymal,kidney collecting duct epithelial cell,kidney collecting duct epithelial cell,kidney collecting duct epithelial cell,kidney collecting duct epithelial cell
4,Enterocyte.dist,epithelial cell of proximal tubule,Hepatocytes,Hepatocytes,epithelial cell of proximal tubule,epithelial cell of proximal tubule,epithelial cell of proximal tubule,epithelial cell of proximal tubule
5,Enterocyte.dist,epithelial cell of proximal tubule,Hepatocytes,Hepatocytes,epithelial cell of proximal tubule,epithelial cell of proximal tubule,epithelial cell of proximal tubule,epithelial cell of proximal tubule
6,enterocyte of epithelium of large intestine,kidney collecting duct epithelial cell,Epithelial cells,Ependymal,kidney collecting duct epithelial cell,kidney collecting duct epithelial cell,kidney collecting duct epithelial cell,kidney collecting duct epithelial cell
7,EP,kidney collecting duct epithelial cell,Epithelial cells,Hepatocytes,kidney collecting duct epithelial cell,kidney collecting duct epithelial cell,kidney collecting duct epithelial cell,kidney collecting duct epithelial cell

In [19]:
scores = scores.round(4)
scores

               celltypist_score  celltypist_ref_score  scANVI_transfer_score
X_scVI_leiden
0                        0.5735                0.6322                 0.5080
1                        0.3751                0.9896                 0.9662
2                        0.7237                0.6877                 0.7301
3                        0.2390                0.9824                 0.9213
4                        0.2908                0.9906                 0.9702
5                        0.2105                0.9782                 0.9543
6                        0.2982                0.9970                 0.9362
7                        0.1793                0.5942                 0.7394

In [11]:
mapping_res

,celltypist_label,celltypist_ref_label,SingleR_main,SingleR_fine,SingleR_user_ref,scANVI_predicted,celltypist_score,celltypist_ref_score,scANVI_transfer_score
X_scVI_leiden,,,,,,,,,
0,Macrophage,macrophage,Monocytes,Macrophages,macrophage,macrophage,0.573521,0.632177,0.507997
1,capillary 2,endothelial cell,Endothelial cells,Endothelial cells,endothelial cell,endothelial cell,0.375120,0.989611,0.966207
2,Stromal cell (DN),endothelial cell,Fibroblasts,Cardiomyocytes,endothelial cell,endothelial cell,0.723670,0.687725,0.730093
3,enterocyte of epithelium of large intestine,kidney collecting duct epithelial cell,Epithelial cells,Ependymal,kidney collecting duct epithelial cell,kidney collecting duct epithelial cell,0.239047,0.982418,0.921272
4,Enterocyte.dist,epithelial cell of proximal tubule,Hepatocytes,Hepatocytes,epithelial cell of proximal tubule,epithelial cell of proximal tubule,0.290825,0.990636,0.970240
5,Enterocyte.dist,epithelial cell of proximal tubule,Hepatocytes,Hepatocytes,epithelial cell of proximal tubule,epithelial cell of proximal tubule,0.210512,0.978177,0.954272
6,enterocyte of epithelium of large intestine,kidney collecting duct epithelial cell,Epithelial cells,Ependymal,kidney collecting duct epithelial cell,kidney collecting duct epithelial cell,0.298205,0.997049,0.936162
7,EP,kidney collecting duct epithelial cell,Epithelial cells,Hepatocytes,kidney collecting duct epithelial cell,kidney collecting duct epithelial cell,0.179310,0.594204,0.739395

In [12]:
mapping_res['cluster'] = mapping_res.index
mapping_res

,celltypist_label,celltypist_ref_label,SingleR_main,SingleR_fine,SingleR_user_ref,scANVI_predicted,celltypist_score,celltypist_ref_score,scANVI_transfer_score,cluster
X_scVI_leiden,,,,,,,,,,
0,Macrophage,macrophage,Monocytes,Macrophages,macrophage,macrophage,0.573521,0.632177,0.507997,0
1,capillary 2,endothelial cell,Endothelial cells,Endothelial cells,endothelial cell,endothelial cell,0.375120,0.989611,0.966207,1
2,Stromal cell (DN),endothelial cell,Fibroblasts,Cardiomyocytes,endothelial cell,endothelial cell,0.723670,0.687725,0.730093,2
3,enterocyte of epithelium of large intestine,kidney collecting duct epithelial cell,Epithelial cells,Ependymal,kidney collecting duct epithelial cell,kidney collecting duct epithelial cell,0.239047,0.982418,0.921272,3
4,Enterocyte.dist,epithelial cell of proximal tubule,Hepatocytes,Hepatocytes,epithelial cell of proximal tubule,epithelial cell of proximal tubule,0.290825,0.990636,0.970240,4
5,Enterocyte.dist,epithelial cell of proximal tubule,Hepatocytes,Hepatocytes,epithelial cell of proximal tubule,epithelial cell of proximal tubule,0.210512,0.978177,0.954272,5
6,enterocyte of epithelium of large intestine,kidney collecting duct epithelial cell,Epithelial cells,Ependymal,kidney collecting duct epithelial cell,kidney collecting duct epithelial cell,0.298205,0.997049,0.936162,6
7,EP,kidney collecting duct epithelial cell,Epithelial cells,Hepatocytes,kidney collecting duct epithelial cell,kidney collecting duct epithelial cell,0.179310,0.594204,0.739395,7

In [13]:
dict_d = mapping_res.to_dict('list', index=True)

In [14]:
dict_d

{'celltypist_label': ['Macrophage',
  'capillary 2',
  'Stromal cell (DN)',
  'enterocyte of epithelium of large intestine',
  'Enterocyte.dist',
  'Enterocyte.dist',
  'enterocyte of epithelium of large intestine',
  'EP'],
 'celltypist_ref_label': ['macrophage',
  'endothelial cell',
  'endothelial cell',
  'kidney collecting duct epithelial cell',
  'epithelial cell of proximal tubule',
  'epithelial cell of proximal tubule',
  'kidney collecting duct epithelial cell',
  'kidney collecting duct epithelial cell'],
 'SingleR_main': ['Monocytes',
  'Endothelial cells',
  'Fibroblasts',
  'Epithelial cells',
  'Hepatocytes',
  'Hepatocytes',
  'Epithelial cells',
  'Epithelial cells'],
 'SingleR_fine': ['Macrophages',
  'Endothelial cells',
  'Cardiomyocytes',
  'Ependymal',
  'Hepatocytes',
  'Hepatocytes',
  'Ependymal',
  'Hepatocytes'],
 'SingleR_user_ref': ['macrophage',
  'endothelial cell',
  'endothelial cell',
  'kidney collecting duct epithelial cell',
  'epithelial cell of proximal tubule',
  'epithelial cell of proximal tubule',
  'kidney collecting duct epithelial cell',
  'kidney collecting duct epithelial cell'],
 'scANVI_predicted': ['macrophage',
  'endothelial cell',
  'endothelial cell',
  'kidney collecting duct epithelial cell',
  'epithelial cell of proximal tubule',
  'epithelial cell of proximal tubule',
  'kidney collecting duct epithelial cell',
  'kidney collecting duct epithelial cell'],
 'celltypist_score': [0.5735207931693991,
  0.3751198156015275,
  0.7236695900226209,
  0.23904675835603523,
  0.290824752055398,
  0.21051211161295952,
  0.29820472101828405,
  0.17931003714027183],
 'celltypist_ref_score': [0.6321773278594067,
  0.989610677133763,
  0.6877247754401633,
  0.9824177130440717,
  0.9906355966891872,
  0.9781767111285953,
  0.9970487260926868,
  0.5942039475657453],
 'scANVI_transfer_score': [0.5079965591430664,
  0.9662070870399475,
  0.7300931811332703,
  0.9212722778320312,
  0.9702402353286743,
  0.9542720913887024,
  0.9361615180969238,
  0.7393954992294312],
 'cluster': ['0', '1', '2', '3', '4', '5', '6', '7']}

In [27]:
def create_annotation_panel(obs, cluster_id='leiden', ground_truth=None, label_columns=['celltypist_label', 'celltypist_ref_label', 'SingleR_main', 'SingleR_fine', 'SingleR_user_ref', 'scANVI_predicted'], score_columns=['celltypist_score', 'celltypist_ref_score', 'scANVI_transfer_score']):
    # Validate label and score columns
    for label_column in label_columns:
        if label_column not in obs.columns:
            label_columns.remove(label_column)
    for score_column in score_columns:
        if score_column not in obs.columns:
            score_columns.remove(score_column)

    # Add ground truth and cluster id at the front if they exist
    if ground_truth is not None and ground_truth in obs.columns:
        label_columns = [ground_truth] + label_columns
    if cluster_id in obs.columns:
        label_columns = [cluster_id] + label_columns
        score_columns = [cluster_id] + score_columns
    else:
        return None

    labels_df = obs[label_columns].groupby(cluster_id).agg(lambda x: x.mode())
    unique_labels = labels_df.stack().unique().tolist()
    labels_df['majority_vote'] = labels_df.mode(axis=1)[0]
    if "cell_type" not in obs.columns:
        labels_df["cell_type"] = labels_df['majority_vote']

    scores_df = obs[score_columns].groupby(cluster_id).agg(lambda x: x.mean())
    scores_df = scores_df.round(4)

    mapping_res = labels_df.merge(right = scores_df, left_index=True, right_index=True)
    mapping_res.insert(0, 'Cluster', mapping_res.index)
    mapping_res_dict = mapping_res.to_dict('list', index=True)

    return {"table": mapping_res_dict, "unique_labels": unique_labels}

In [22]:
mapping_res.insert(0, 'Cluster', mapping_res.index)
mapping_res

,Cluster,celltypist_label,celltypist_ref_label,SingleR_main,SingleR_fine,SingleR_user_ref,scANVI_predicted,celltypist_score,celltypist_ref_score,scANVI_transfer_score,cluster
X_scVI_leiden,,,,,,,,,,,
0,0,Macrophage,macrophage,Monocytes,Macrophages,macrophage,macrophage,0.573521,0.632177,0.507997,0
1,1,capillary 2,endothelial cell,Endothelial cells,Endothelial cells,endothelial cell,endothelial cell,0.375120,0.989611,0.966207,1
2,2,Stromal cell (DN),endothelial cell,Fibroblasts,Cardiomyocytes,endothelial cell,endothelial cell,0.723670,0.687725,0.730093,2
3,3,enterocyte of epithelium of large intestine,kidney collecting duct epithelial cell,Epithelial cells,Ependymal,kidney collecting duct epithelial cell,kidney collecting duct epithelial cell,0.239047,0.982418,0.921272,3
4,4,Enterocyte.dist,epithelial cell of proximal tubule,Hepatocytes,Hepatocytes,epithelial cell of proximal tubule,epithelial cell of proximal tubule,0.290825,0.990636,0.970240,4
5,5,Enterocyte.dist,epithelial cell of proximal tubule,Hepatocytes,Hepatocytes,epithelial cell of proximal tubule,epithelial cell of proximal tubule,0.210512,0.978177,0.954272,5
6,6,enterocyte of epithelium of large intestine,kidney collecting duct epithelial cell,Epithelial cells,Ependymal,kidney collecting duct epithelial cell,kidney collecting duct epithelial cell,0.298205,0.997049,0.936162,6
7,7,EP,kidney collecting duct epithelial cell,Epithelial cells,Hepatocytes,kidney collecting duct epithelial cell,kidney collecting duct epithelial cell,0.179310,0.594204,0.739395,7

In [28]:
res = create_annotation_panel(adata.obs, cluster_id='X_scVI_leiden')

/tmp/ipykernel_650/1716285926.py:19: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  labels_df = obs[label_columns].groupby(cluster_id).agg(lambda x: x.mode())
/tmp/ipykernel_650/1716285926.py:25: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  scores_df = obs[score_columns].groupby(cluster_id).agg(lambda x: x.mean())

In [29]:
res

{'table': {'Cluster': ['0', '1', '2', '3', '4', '5', '6', '7'],
  'celltypist_label': ['Macrophage',
   'capillary 2',
   'Stromal cell (DN)',
   'enterocyte of epithelium of large intestine',
   'Enterocyte.dist',
   'Enterocyte.dist',
   'enterocyte of epithelium of large intestine',
   'EP'],
  'celltypist_ref_label': ['macrophage',
   'endothelial cell',
   'endothelial cell',
   'kidney collecting duct epithelial cell',
   'epithelial cell of proximal tubule',
   'epithelial cell of proximal tubule',
   'kidney collecting duct epithelial cell',
   'kidney collecting duct epithelial cell'],
  'SingleR_main': ['Monocytes',
   'Endothelial cells',
   'Fibroblasts',
   'Epithelial cells',
   'Hepatocytes',
   'Hepatocytes',
   'Epithelial cells',
   'Epithelial cells'],
  'SingleR_fine': ['Macrophages',
   'Endothelial cells',
   'Cardiomyocytes',
   'Ependymal',
   'Hepatocytes',
   'Hepatocytes',
   'Ependymal',
   'Hepatocytes'],
  'SingleR_user_ref': ['macrophage',
   'endothelial cell',
   'endothelial cell',
   'kidney collecting duct epithelial cell',
   'epithelial cell of proximal tubule',
   'epithelial cell of proximal tubule',
   'kidney collecting duct epithelial cell',
   'kidney collecting duct epithelial cell'],
  'scANVI_predicted': ['macrophage',
   'endothelial cell',
   'endothelial cell',
   'kidney collecting duct epithelial cell',
   'epithelial cell of proximal tubule',
   'epithelial cell of proximal tubule',
   'kidney collecting duct epithelial cell',
   'kidney collecting duct epithelial cell'],
  'majority_vote': ['macrophage',
   'endothelial cell',
   'endothelial cell',
   'kidney collecting duct epithelial cell',
   'epithelial cell of proximal tubule',
   'epithelial cell of proximal tubule',
   'kidney collecting duct epithelial cell',
   'kidney collecting duct epithelial cell'],
  'cell_type': ['macrophage',
   'endothelial cell',
   'endothelial cell',
   'kidney collecting duct epithelial cell',
   'epithelial cell of proximal tubule',
   'epithelial cell of proximal tubule',
   'kidney collecting duct epithelial cell',
   'kidney collecting duct epithelial cell'],
  'celltypist_score': [0.5735,
   0.3751,
   0.7237,
   0.239,
   0.2908,
   0.2105,
   0.2982,
   0.1793],
  'celltypist_ref_score': [0.6322,
   0.9896,
   0.6877,
   0.9824,
   0.9906,
   0.9782,
   0.997,
   0.5942],
  'scANVI_transfer_score': [0.5080000162124634,
   0.9661999940872192,
   0.7300999760627747,
   0.9212999939918518,
   0.9702000021934509,
   0.9542999863624573,
   0.9362000226974487,
   0.7394000291824341]},
 'unique_labels': ['Macrophage',
  'macrophage',
  'Monocytes',
  'Macrophages',
  'capillary 2',
  'endothelial cell',
  'Endothelial cells',
  'Stromal cell (DN)',
  'Fibroblasts',
  'Cardiomyocytes',
  'enterocyte of epithelium of large intestine',
  'kidney collecting duct epithelial cell',
  'Epithelial cells',
  'Ependymal',
  'Enterocyte.dist',
  'epithelial cell of proximal tubule',
  'Hepatocytes',
  'EP']}